# Example configuration for the ventilation component
ventilation:
  # List of CO2 sensor entity IDs
  co2_sensors:
    - sensor.esphome_web_79a218_scd4x_co2
    - sensor.another_co2_sensor  # Optional: add more sensors
  
  # Air quality index setpoint (0.0 - 5.0)
  setpoint: 0.5
  
  # Fan output range (0-255)
  min_fan_output: 0
  max_fan_output: 255
  
  # PID controller gains
  kp: 25.5  # Proportional gain
  
  # Ki time constants for each CO2 index level (seconds to reach max fan speed)
  # Index 0: 400-650 ppm   -> 1 hour
  # Index 1: 650-1500 ppm  -> 30 minutes
  # Index 2: 1500-2000 ppm -> 15 minutes
  # Index 3: 2000-2500 ppm -> 7.5 minutes
  # Index 4: 2500-5000 ppm -> 3.75 minutes
  # Index 5: >5000 ppm     -> 2.5 minutes
  ki_times: [3600, 1800, 900, 450, 225, 150]
  
  # Update interval in seconds (10-3600)
  update_interval: 300
  
  # Entity ID for the ramses_cc remote
  entity_id: "remote.29_162275"
